//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QiDianData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NovelLibrary
    {
        public int Id { get; set; }
        public string NovelName { get; set; }
        public string RealName { get; set; }
        public string AuthorName { get; set; }
        public Nullable<int> NovelType { get; set; }
        public Nullable<int> IsBot { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
