//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QiDianData.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QiDianSogouEntities : DbContext
    {
        public QiDianSogouEntities()
            : base("name=QiDianSogouEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<NovelLibrary> NovelLibrary { get; set; }
        public DbSet<ResultLiks> ResultLiks { get; set; }
        public DbSet<WhiteList> WhiteList { get; set; }
        public DbSet<BlackList> BlackList { get; set; }
    }
}
