//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QiDianData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultLiks
    {
        public int Id { get; set; }
        public Nullable<System.Guid> Rid { get; set; }
        public Nullable<int> NovelId { get; set; }
        public string NovelName { get; set; }
        public string RealName { get; set; }
        public string AuthorName { get; set; }
        public string LinkTitle { get; set; }
        public string LinkAbstract { get; set; }
        public string LinkUrl { get; set; }
        public string Keyword { get; set; }
        public string BeiYong { get; set; }
        public string Domain { get; set; }
        public string TopDomain { get; set; }
        public Nullable<int> BlackId { get; set; }
        public Nullable<int> States { get; set; }
    }
}
