//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace kuerjiudian.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class huangguan_share
    {
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> Sender { get; set; }
        public string Label { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<bool> IsReaded { get; set; }
        public string Abstract { get; set; }
        public Nullable<int> CategoryId { get; set; }
    }
}
