//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace kuerjiudian.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kuerhotelsEntities : DbContext
    {
        public kuerhotelsEntities()
            : base("name=kuerhotelsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<huangguan_roles> huangguan_roles { get; set; }
        public DbSet<huangguan_share> huangguan_share { get; set; }
        public DbSet<huangguan_sharereply> huangguan_sharereply { get; set; }
        public DbSet<huangguan_shareusers> huangguan_shareusers { get; set; }
        public DbSet<huangguan_user> huangguan_user { get; set; }
        public DbSet<huangguan_category> huangguan_category { get; set; }
        public DbSet<ipfiles> ipfiles { get; set; }
    }
}
