//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace kuerjiudian.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class huangguan_user
    {
        public System.Guid ID { get; set; }
        public string LoginName { get; set; }
        public Nullable<System.Guid> LoginPwd { get; set; }
        public string NickName { get; set; }
        public string UserPhone { get; set; }
        public string HeadIcon { get; set; }
        public string RoleId { get; set; }
        public string UserEmail { get; set; }
        public Nullable<int> status { get; set; }
        public string Error { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Token { get; set; }
        public string YZM { get; set; }
        public string Gender { get; set; }
    }
}
